<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
		<SupportedOSPlatformVersion>10.0.14393.0</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Xenostrap.Platform.Windows</RootNamespace>
		<AssemblyName>Xenostrap.Platform.Windows</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Xenostrap.Core\Xenostrap.Core.csproj" />
		<ProjectReference Include="..\Xenostrap.Platform.Abstractions\Xenostrap.Platform.Abstractions.csproj" />
	</ItemGroup>
</Project>
