<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Xenostrap.Desktop.Linux</RootNamespace>
		<AssemblyName>Xenostrap</AssemblyName>
		<RuntimeIdentifiers>linux-x64;linux-arm64;linux-musl-x64;linux-musl-arm64</RuntimeIdentifiers>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia.Wayland" Version="12.1.0" />
		<ProjectReference Include="..\Xenostrap.Desktop\Xenostrap.Desktop.csproj" />
		<ProjectReference Include="..\Xenostrap.Platform.Linux\Xenostrap.Platform.Linux.csproj" />
	</ItemGroup>
</Project>
